PAT_FC = "fc([0-9]+)/([0-9]+)"
PAT_PC = "port-channel([0-9]+)"
PAT_FCIP = "fcip([0-9]+)"
ON = "on"
OFF = "off"
AUTO = "auto"
SHUTDOWN = "shutdown"
NO_SHUTDOWN = "no shutdown"
ACTIVE = "active"
VALID_VSAN = range(1, 4095)  # 1-4094
RESERVED_VSAN = [1, 4079, 4094]
BASIC = "basic"
ENHANCED = "enhanced"
PERMIT = "permit"
DENY = "deny"
VALID_PC_RANGE = range(1, 257)  # 1-256
VALID_FCIP_RANGE = range(1, 513)  # 1-512
VALID_FCIP_PROFILE_RANGE = range(1, 513)  # 1-512
SUSPEND = "suspend"
NO_SUSPEND = "no suspend"
OUT_OF_SERVICE = "outOfServc"
VALID_PC_CHANNEL_MODES = [ON, ACTIVE]
