# show zone status vsan <>
ZONE_VSAN_ID = 'vsan_id'
ZONE_DEFAULT_ZONE = 'default_zone'
ZONE_DISTRIBUTE = 'distribute'
ZONE_INTEROP = 'interop'
ZONE_MODE = 'mode'
ZONE_MERGE_CONTROL = 'merge_control'
ZONE_SESSION = 'session'
ZONE_SMART_ZONE = 'smart_zoning'
ZONE_DETAILS = 'zone_details'

# show zone name vsan <>
ZONE_NAME = 'zone_name'
ZONE_NAME_VSAN_ID = 'zone_vsan_id'
# ZONE_MEMBERS = ['TABLE_zone_member']['ROW_zone_member']
ZONE_MEMBER_TYPE = 'zone_member_type'
ZONE_MEMBER_WWN = 'wwn'
ZONE_MEMBER_INTERFACE = 'intf_fc'
ZONE_MEMBER_DEVALIAS = 'dev_alias'
ZONE_MEMBER_IPADDR = 'ipaddr'
ZONE_MEMBER_SYMNODENAME = 'symnodename'
ZONE_MEMBER_FWWN = 'wwn'
ZONE_MEMBER_SWWN = 'wwn'
ZONE_MEMBER_FCID = 'fcid'
ZONE_MEMBER_INTERFACE_PC = 'intf_port_ch'
ZONE_MEMBER_FCALIAS = 'fcalias_name'
ZONE_MEMBER_FCALIAS_VSANID = 'fcalias_vsan_id'
